import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import ToastProvicer from "@/components/toastProvider/ToastProvicer";
import Footer from "@/layouts/footer/Footer";
import Header from "@/layouts/header/Header";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ToastProvicer />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
